FROM node:20-alpine
WORKDIR /app
COPY {{appSourcePath}}package*.json ./
RUN npm install && npm cache clean --force
COPY {{appSourcePath}} .
EXPOSE {{port}}
{{#if healthCheck}}
HEALTHCHECK --interval={{healthCheck.interval}}s CMD curl -f http://localhost:{{port}}{{healthCheck.path}} || exit 1
{{/if}}
{{#if startupCommand}}
CMD {{startupCommand}}
{{/if}}