FROM python:3.11-alpine
WORKDIR /app
COPY {{appSourcePath}}requirements*.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY {{appSourcePath}} .
EXPOSE {{port}}
{{#if healthCheck}}
HEALTHCHECK --interval={{healthCheck.interval}}s CMD curl -f http://localhost:{{port}}{{healthCheck.path}} || exit 1
{{/if}}
{{#if startupCommand}}
CMD {{startupCommand}}
{{/if}}