/**
 * @fileoverview Tests for lib/utils/external-readme.js
 * Validates README context building and generated content against real template and CLI behavior.
 *
 * This test is in tests/local/ because it requires template file access which can be
 * problematic in CI environments where templates may not be copied correctly.
 */

const path = require('path');
const fs = require('fs');
const handlebars = require('handlebars');

// Mock the template loading to avoid file system issues in CI
jest.mock('../../../../lib/utils/external-readme', () => {
  const actualModule = jest.requireActual('../../../../lib/utils/external-readme');
  const path = require('path');
  const fs = require('fs');
  const handlebars = require('handlebars');
  const { getProjectRoot } = require('../../../../lib/utils/paths');

  // Try to load the real template, but fall back to a mock if it doesn't exist
  let templateContent = null;
  let compiledTemplate = null;

  function loadTemplate() {
    if (compiledTemplate) {
      return compiledTemplate;
    }

    try {
      const projectRoot = getProjectRoot();
      const templatePath = path.join(projectRoot, 'templates', 'external-system', 'README.md.hbs');
      if (fs.existsSync(templatePath)) {
        templateContent = fs.readFileSync(templatePath, 'utf8');
      }
    } catch (error) {
      // Template not found, will use mock
    }

    // Use real template if available, otherwise use a mock template matching templates/external-system/README.md.hbs
    if (!templateContent) {
      templateContent = `# {{displayName}}

{{description}}

## System Information

- **System Key**: \`{{systemKey}}\`
- **System Type**: \`{{systemType}}\`
- **Datasources**: {{datasourceCount}}

## Files

- \`application{{fileExt}}\` – Application configuration with \`app\` and \`externalIntegration\` blocks
- \`{{systemKey}}-system{{fileExt}}\` – External system definition (authentication, OpenAPI/MCP, RBAC)
{{#each datasources}}
- \`{{fileName}}\` – Datasource: {{displayName}}
{{/each}}
- \`env.template\` – Environment variables template (secrets, API keys)
- \`{{systemKey}}-deploy.json\` – Deployment manifest (generated by \`aifabrix json {{appName}}\`)
- \`deploy.js\` – Deploy script for the integration
- \`wizard.yaml\` – Wizard configuration (if created via wizard)

Optional: \`{{rbacOptionalFile}}\` – Roles and permissions merged into the system when present.

## Quick Start

Login to your controller
\`\`\`bash
aifabrix auth config --set-controller <url> --set-environment dev
aifabrix login
\`\`\`

### 1. Extend External System

Use the interactive wizard to extend your existing system:

\`\`\`bash
aifabrix wizard --app {{appName}}
\`\`\`

### 2. Configure Authentication and Datasources

Edit files in \`integration/{{appName}}/\`:

- **Authentication**: \`{{systemKey}}-system{{fileExt}}\` (auth type, credentials placeholders)
- **Field mappings**: \`{{systemKey}}-datasource-*{{fileExt}}\` (dimensions, attributes, operations)
- **Credential and configuration**: \`env.template\` (security settings and configuration variables)

### 3. Validate configuration (local only)

\`aifabrix validate\` runs **on your machine** — no dataplane.

\`\`\`bash
aifabrix validate {{appName}}
\`\`\`

### 4. Repair Deployment Manifest

**Run repair regularly.**

\`\`\`bash
aifabrix repair {{appName}}
\`\`\`

Options:
  --dry-run   Report changes only; do not write
  --rbac      Ensure RBAC permissions per datasource

### 5. Upload to dataplane

\`\`\`bash
aifabrix upload {{appName}}
\`\`\`

## Testing

| Command | Calls dataplane? |
| \`aifabrix validate {{appName}}\` | No |
| \`aifabrix test {{appName}}\` | No |
| \`aifabrix test-integration {{appName}}\` | Yes |

### Local checks (no API)

\`\`\`bash
aifabrix validate {{appName}}
aifabrix test {{appName}}
\`\`\`

### Integration tests (dataplane API)

\`\`\`bash
aifabrix test-integration {{appName}}
\`\`\`

### End-to-end tests (dataplane API)

\`\`\`bash
aifabrix test-e2e {{appName}}
\`\`\`

### E2E tests per datasource

{{#if hasDatasources}}
\`\`\`bash
{{#each datasources}}
# {{displayName}}
aifabrix datasource test-e2e {{datasourceKey}} --app {{../appName}}

{{/each}}
\`\`\`
{{/if}}

## Deployment

Deploy via miso-controller pipeline (same as regular apps).

\`\`\`bash
aifabrix deploy {{appName}}
\`\`\`

## Troubleshooting

- **Local validation errors**: Run \`aifabrix validate {{appName}}\` — files on disk only.
- **Deployment / auth**: Run \`aifabrix auth config --set-controller <url> --set-environment <env>\` and \`aifabrix login\` before \`aifabrix deploy\`.
- **File not found**: Run commands from the project root (where \`package.json\` and \`integration/\` live).`;
    }

    compiledTemplate = handlebars.compile(templateContent);
    return compiledTemplate;
  }

  // Override generateExternalReadmeContent to use our template loader
  const originalGenerate = actualModule.generateExternalReadmeContent;
  function generateExternalReadmeContent(params = {}) {
    const template = loadTemplate();
    const context = actualModule.buildExternalReadmeContext(params);
    return template(context);
  }

  return {
    ...actualModule,
    generateExternalReadmeContent
  };
});

const {
  buildExternalReadmeContext,
  generateExternalReadmeContent
} = require('../../../../lib/utils/external-readme');

describe('external-readme', () => {
  describe('buildExternalReadmeContext', () => {
    it('returns defaults when params is empty', () => {
      const ctx = buildExternalReadmeContext({});
      expect(ctx.appName).toBe('external-system');
      expect(ctx.systemKey).toBe('external-system');
      expect(ctx.displayName).toBe('External System');
      expect(ctx.systemType).toBe('openapi');
      expect(ctx.fileExt).toBe('.json');
      expect(ctx.rbacOptionalFile).toBe('rbac.json');
      expect(ctx.datasourceCount).toBe(0);
      expect(ctx.hasDatasources).toBe(false);
      expect(ctx.datasources).toEqual([]);
    });

    it('uses provided appName and systemKey', () => {
      const ctx = buildExternalReadmeContext({
        appName: 'myapp',
        systemKey: 'myapp',
        displayName: 'My App',
        description: 'Test'
      });
      expect(ctx.appName).toBe('myapp');
      expect(ctx.systemKey).toBe('myapp');
      expect(ctx.displayName).toBe('My App');
      expect(ctx.description).toBe('Test');
    });

    it('normalizes datasources with -datasource- filename pattern (not -deploy-)', () => {
      const ctx = buildExternalReadmeContext({
        systemKey: 'hubspot',
        datasources: [
          { entityType: 'company', displayName: 'Company' },
          { entityType: 'contact', displayName: 'Contact' }
        ]
      });
      expect(ctx.datasources).toHaveLength(2);
      expect(ctx.datasources[0].fileName).toBe('hubspot-datasource-company.json');
      expect(ctx.datasources[1].fileName).toBe('hubspot-datasource-contact.json');
      expect(ctx.datasources[0].fileName).not.toMatch(/-deploy-/);
    });

    it('derives fileName from key like "systemKey-deploy-entity" as systemKey-datasource-entity.json', () => {
      const ctx = buildExternalReadmeContext({
        systemKey: 'hubspot',
        datasources: [
          { key: 'hubspot-deploy-company', displayName: 'Company' },
          { key: 'hubspot-deploy-contact', displayName: 'Contact' }
        ]
      });
      expect(ctx.datasources[0].fileName).toBe('hubspot-datasource-company.json');
      expect(ctx.datasources[1].fileName).toBe('hubspot-datasource-contact.json');
    });

    it('keeps provided fileName when present', () => {
      const ctx = buildExternalReadmeContext({
        systemKey: 'hubspot',
        datasources: [
          { fileName: 'hubspot-datasource-company.json', displayName: 'Company' }
        ]
      });
      expect(ctx.datasources[0].fileName).toBe('hubspot-datasource-company.json');
    });

    it('handles non-array datasources as empty', () => {
      expect(buildExternalReadmeContext({ systemKey: 'x', datasources: null }).datasources).toEqual([]);
      expect(buildExternalReadmeContext({ systemKey: 'x', datasources: undefined }).datasources).toEqual([]);
    });

    it('includes datasourceKey on each normalized datasource for E2E commands', () => {
      const ctx = buildExternalReadmeContext({
        systemKey: 'hubspot-demo',
        datasources: [
          { key: 'hubspot-demo-companies-datasource', displayName: 'HubSpot Companies' },
          { key: 'hubspot-demo-contacts-datasource', displayName: 'HubSpot Contacts' }
        ]
      });
      expect(ctx.datasources[0].datasourceKey).toBe('hubspot-demo-companies-datasource');
      expect(ctx.datasources[1].datasourceKey).toBe('hubspot-demo-contacts-datasource');
    });

    it('uses fileExt param for default datasource filenames', () => {
      const ctx = buildExternalReadmeContext({
        systemKey: 'myapp',
        fileExt: '.yaml',
        datasources: [{ entityType: 'users', displayName: 'Users' }]
      });
      expect(ctx.fileExt).toBe('.yaml');
      expect(ctx.datasources[0].fileName).toBe('myapp-datasource-users.yaml');
      expect(ctx.rbacOptionalFile).toBe('rbac.yaml');
    });
  });

  describe('generateExternalReadmeContent', () => {
    it('produces README that references -deploy.json (not application-schema.json)', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('myext-deploy.json');
      expect(out).not.toContain('application-schema.json');
    });

    it('produces deploy command without --controller or --environment flags', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).not.toMatch(/aifabrix deploy \w+ --controller/);
      expect(out).not.toMatch(/aifabrix deploy \w+ --environment/);
    });

    it('tells user to run auth config and login before deploy', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('aifabrix auth config');
      expect(out).toContain('aifabrix login');
    });

    it('includes datasource file names in Files section when provided', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'hubspot',
        appName: 'hubspot',
        datasources: [
          { entityType: 'company', displayName: 'Company' },
          { entityType: 'contact', displayName: 'Contact' }
        ]
      });
      expect(out).toContain('hubspot-datasource-company.json');
      expect(out).toContain('hubspot-datasource-contact.json');
    });

    it('includes validate without --type external', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('aifabrix validate myext');
      expect(out).not.toContain('validate myext --type external');
    });

    it('documents local validate vs dataplane-backed tests', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('## Validate and test');
      expect(out).toContain('| Command | Network |');
      expect(out).toContain('Off — schemas and files only');
      expect(out).toContain('On — needs login + dataplane');
    });

    it('includes test, test-integration, and test-e2e commands', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('aifabrix test ');
      expect(out).toContain('aifabrix test-integration ');
      expect(out).toContain('aifabrix test-e2e ');
    });

    it('includes Typical workflow with login and auth config', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('## Typical workflow');
      expect(out).toContain('aifabrix auth config');
      expect(out).toContain('aifabrix login');
    });

    it('includes repair section and command', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('## Repair');
      expect(out).toContain('aifabrix repair ');
      expect(out).toContain('--dry-run');
      expect(out).toContain('--rbac');
    });

    it('includes upload command in workflow', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('**Publish**');
      expect(out).toContain('aifabrix upload ');
    });

    it('includes deploy.js and wizard.yaml in Files section', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        datasources: []
      });
      expect(out).toContain('deploy.js');
      expect(out).toContain('wizard.yaml');
    });

    it('includes datasource test-e2e commands with key and --app', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'hubspot-demo',
        appName: 'hubspot-demo',
        datasources: [
          { key: 'hubspot-demo-companies-datasource', displayName: 'HubSpot Companies' },
          { key: 'hubspot-demo-contacts-datasource', displayName: 'HubSpot Contacts' }
        ]
      });
      expect(out).toContain('Single datasource E2E');
      expect(out).toContain('aifabrix datasource test-e2e hubspot-demo-companies-datasource --app hubspot-demo');
      expect(out).toContain('aifabrix datasource test-e2e hubspot-demo-contacts-datasource --app hubspot-demo');
    });

    it('uses application and system fileExt in Files section', () => {
      const out = generateExternalReadmeContent({
        systemKey: 'myext',
        appName: 'myext',
        fileExt: '.json',
        datasources: []
      });
      expect(out).toContain('application.json');
      expect(out).toContain('myext-system.json');
      expect(out).toContain('`rbac.json`');
    });
  });
});
